### ISSUE TITLE
#error "This board does not support this sample..."

### ISSUE THREAD

**Issue by danchouzhou** [OpenNuvoton/NuEdu-UNO#11]
Hello, 
Got an error while compiling CAN_BUS\examples\
can_.h:14:6: error: #error "This board does not support this sample..."

**Comment by egbert-h** [comment]
> Hello,
> Got an error while compiling CAN_BUS\examples
> can_.h:14:6: error: #error "This board does not support this sample..."

HI, 
this board does not support this sample due to internal naming space issue with arduino core.
And the board need external CAN hardware to doing transfer so we does not plan to support the example.

**Comment by chhsieh3** [comment]
Close old issue

**Comment by chhsieh3** [comment]
Close old issue
