### ISSUE TITLE
还能支持其他芯片么？ Support other chips？

### ISSUE THREAD

**Issue by happysoul** [OpenNuvoton/NuEdu-UNO#12]
支持列表里的芯片买不到，其他芯片一直都不支持，相似的芯片可以修改一下参数兼容，但是其他型号的芯片想兼容就很困难了
pin能多一点，程序存储能大一点的，是否有计划添加到arduino

Only 2 chips supported by this project，how about others，it's hardly to get supported chips above from net
Any plan to support other chips？

**Comment by chhsieh3** [comment]
Close old issue
