### ISSUE TITLE
安装开发板支持包失败

### ISSUE THREAD

**Issue by RealWangzhihong** [OpenNuvoton/NuEdu-UNO#13]
我在中国无法通过arduino自动下载开发板支持包，我下载了bz2包和json包，并通过HFS建立了本地服务器生成本地地址用于arduino从本地安装开发板支持包，我曾经用这个办法安装了CH552支持包，但这个项目却无法通过这个办法安装，如果有懂的人，请帮忙指导一下，谢谢

**Comment by chhsieh3** [comment]
Close issue due to unknown CH552
