### ISSUE TITLE
EEPROM.update EEPROM.get

### ISSUE THREAD

**Issue by KenaiFrankenstein** [OpenNuvoton/NuEdu-UNO#14]
The EEPROM library works but is incomplete, the update() and get() commands are not implemented

**Comment by stanlytw** [comment]
Dear KenaiFrankenstein:
        We have an new commit for this issue. However, due to our hardware property, it requires an external EEPROM connected via i2c(Wire) interface.  Then you can enjoy the library. Thanks.

**Comment by chhsieh3** [comment]
Close fixed issue
